### ISSUE TITLE
Broken on nightly due to rustfmt bug

### ISSUE THREAD

**Issue by singron** [Smithay/wayland-rs#257]
See https://github.com/rust-lang/rustfmt/issues/3463

The broken call to rustfmt happens here: https://github.com/Smithay/wayland-rs/blob/f7ce15ee3870aad470780cb9a45765e2469634e7/wayland-scanner/src/lib.rs#L139

The error looks like this

```none
error: expected open delimiter
    --> <snip>/target/debug/build/wayland-server-37833afa0b2b7b90/out/wayland_api.rs:3208:24
     |
3208 |     bitflags! bitflags ! { # [ doc = <snip>
     |                        ^ expected open delimiter

```

If you comment out the rustfmt call, then the output is fine. You could probably put a rustfmt in PATH that does nothing like /bin/true.

**Comment by vberger** [comment]
This looks like it's going to be quickly fixed by https://github.com/rust-lang/rustfmt/pull/3464

**Comment by martinellison** [comment]
This is breaking my build, and presumably any build that contains wayland_client and nightly, so could you please fix this as soon as possible? Is there a work around?

**Comment by AlmightyFloppyFish** [comment]
I'm still having this issue, and I'm using nightly _**cargo 1.35.0-nightly (0e35bd8af 2019-03-13)**_

**Comment by vberger** [comment]
According to https://github.com/vulkano-rs/vulkano/issues/1184#issuecomment-477108512 the rustfmt bug is fixed in `nightly-2019-03-23`.
